files: ^Quantum-Music/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml
    args:
    - "--unsafe"
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: debug-statements
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    args:
    - "-l 100"
- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.8.4
  hooks:
  - id: flake8
    args:
    - "--max-line-length=100"
    - "--per-file-ignores=*/__init__.py:F401"
